.TH "Referència del Directori src" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referència del Directori src
.SH SYNOPSIS
.br
.PP
.SS "Fitxers"

.in +1c
.ti -1c
.RI "fitxer \fBCasella\&.java\fP"
.br
.RI "Classe \fBCasella\fP\&. "
.ti -1c
.RI "fitxer \fBColor\&.java\fP"
.br
.RI "Ennum \fBColor\fP\&. "
.ti -1c
.RI "fitxer \fBContadors\&.java\fP"
.br
.RI "Classe \fBContadors\fP\&. "
.ti -1c
.RI "fitxer \fBCPU\&.java\fP"
.br
.RI "Classe \fBCPU\fP\&. "
.ti -1c
.RI "fitxer \fBEscacs\&.java\fP"
.br
.RI "Classe \fBEscacs\fP\&. "
.ti -1c
.RI "fitxer \fBEstatTauler\&.java\fP"
.br
.RI "Ennum \fBEstatTauler\fP\&. "
.ti -1c
.RI "fitxer \fBExcepcioG\&.java\fP"
.br
.RI "Classe \fBExcepcioG\fP\&. "
.ti -1c
.RI "fitxer \fBFitxer\&.java\fP"
.br
.RI "Classe \fBFitxer\fP\&. "
.ti -1c
.RI "fitxer \fBHuma\&.java\fP"
.br
.RI "Classe \fBHuma\fP\&. "
.ti -1c
.RI "fitxer \fBJocGrafic\&.java\fP"
.br
.RI "Classe \fBJocGrafic\fP\&. "
.ti -1c
.RI "fitxer \fBJocText\&.java\fP"
.br
.RI "Classe \fBJocText\fP\&. "
.ti -1c
.RI "fitxer \fBJson\&.java\fP"
.br
.RI "Classe \fBJson\fP\&. "
.ti -1c
.RI "fitxer \fBJugada\&.java\fP"
.br
.RI "Classe \fBJugada\fP\&. "
.ti -1c
.RI "fitxer \fBJugador\&.java\fP"
.br
.ti -1c
.RI "fitxer \fBMinIMax\&.java\fP"
.br
.RI "Interfície \fBMinIMax\fP\&. "
.ti -1c
.RI "fitxer \fBMinIMaxParalel\&.java\fP"
.br
.RI "Classe \fBMinIMaxParalel\fP\&. "
.ti -1c
.RI "fitxer \fBMinIMaxSequencial\&.java\fP"
.br
.RI "Classe \fBMinIMaxSequencial\fP\&. "
.ti -1c
.RI "fitxer \fBMotorCPU\&.java\fP"
.br
.RI "Classe \fBMotorCPU\fP\&. "
.ti -1c
.RI "fitxer \fBMoviment\&.java\fP"
.br
.RI "Classe \fBMoviment\fP\&. "
.ti -1c
.RI "fitxer \fBMovimentCombinat\&.java\fP"
.br
.RI "Classe \fBMovimentCombinat\fP\&. "
.ti -1c
.RI "fitxer \fBMovimentDiagonal\&.java\fP"
.br
.RI "Classe \fBMovimentDiagonal\fP\&. "
.ti -1c
.RI "fitxer \fBMovimentEspecial\&.java\fP"
.br
.RI "Classe \fBMovimentEspecial\fP\&. "
.ti -1c
.RI "fitxer \fBMovimentRectilini\&.java\fP"
.br
.RI "Classe \fBMovimentRectilini\fP\&. "
.ti -1c
.RI "fitxer \fBPair\&.java\fP"
.br
.RI "Classe \fBPair\fP\&. "
.ti -1c
.RI "fitxer \fBPartida\&.java\fP"
.br
.RI "Classe \fBEscacs\fP\&. "
.ti -1c
.RI "fitxer \fBPeca\&.java\fP"
.br
.RI "Classe \fBPeca\fP\&. "
.ti -1c
.RI "fitxer \fBPecaGrafica\&.java\fP"
.br
.RI "Classe \fBPecaGrafica\fP\&. "
.ti -1c
.RI "fitxer \fBPosicio\&.java\fP"
.br
.RI "Classe \fBPosicio\fP\&. "
.ti -1c
.RI "fitxer \fBRajola\&.java\fP"
.br
.RI "Classe \fBRajola\fP\&. "
.ti -1c
.RI "fitxer \fBResultatJugada\&.java\fP"
.br
.RI "Enum \fBResultatJugada\fP\&. "
.ti -1c
.RI "fitxer \fBResultatPartida\&.java\fP"
.br
.RI "Enum \fBResultatPartida\fP\&. "
.ti -1c
.RI "fitxer \fBTauler\&.java\fP"
.br
.RI "Classe \fBTauler\fP\&. "
.ti -1c
.RI "fitxer \fBTipusExcepcioG\&.java\fP"
.br
.RI "Enum \fBTipusExcepcioG\fP\&. "
.ti -1c
.RI "fitxer \fBTipusPeca\&.java\fP"
.br
.RI "Classe \fBTipusPeca\fP\&. "
.in -1c
