.TH "src/Casella.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Casella.java \- Classe \fBCasella\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCasella\fP"
.br
.RI "Una casella d'un \fBTauler\fP\&. Classe contenidora\&. Pot contenir una Peça\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBCasella\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
