.TH "Classe" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classe
.SH SYNOPSIS
.br
.PP
.SH "Descripció Detallada"
.PP 

.PP
\fBAutor\fP
.RS 4
Eloi Quintana u1963141
.RE
.PP
els 2 contadors per a cada \fBColor\fP\&. 

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
