.TH "src/Color.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Color.java \- Ennum \fBColor\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBColor\fP"
.br
.RI "\fBColor\fP d'una peça que pot ser blanca o negra\&. Adicionalment s'hi afegeix un element neutre(capColor)\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Ennum \fBColor\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
