.TH "src/Contadors.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Contadors.java \- Classe \fBContadors\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContadors\fP"
.br
.RI "Gestiona els dos contadors per a cada color\&. Innacció i \fBEscacs\fP seguits\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBContadors\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
