.TH "src/Escacs.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Escacs.java \- Classe \fBEscacs\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEscacs\fP"
.br
.RI "Classe d'entrada al programa\&. Pregunta en quin mode es vol executar el joc: la versio gràfica o text/terminal\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBEscacs\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
