.TH "src/ExcepcioG.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ExcepcioG.java \- Classe \fBExcepcioG\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExcepcioG\fP"
.br
.RI "Classe ExepcioG que gestiona el tipus de ExepcionsG (\fBTipusExcepcioG\fP)\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBExcepcioG\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
