.TH "ExcepcioG" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExcepcioG \- Classe ExepcioG que gestiona el tipus de ExepcionsG (\fBTipusExcepcioG\fP)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Hereta de Exception\&.
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBTipusExcepcioG\fP \fBgetTipus\fP ()"
.br
.in -1c
.SS "Funcions de Paquet"

.in +1c
.ti -1c
.RI "\fBExcepcioG\fP (\fBTipusExcepcioG\fP t)"
.br
.in -1c
.SS "Atributs Privats"

.in +1c
.ti -1c
.RI "final \fBTipusExcepcioG\fP \fBexc\fP"
.br
.in -1c
.SH "Descripció Detallada"
.PP 
Classe ExepcioG que gestiona el tipus de ExepcionsG (\fBTipusExcepcioG\fP)\&. 


.PP
\fBNota\fP
.RS 4
S'utilitza a \fBPartida\fP i \fBJson\fP\&. 
.RE
.PP
\fBAutor\fP
.RS 4
Eloi Quintana Ferrer 
.PP
u1963141 
.RE
.PP

.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "ExcepcioG\&.ExcepcioG (\fBTipusExcepcioG\fP t)\fC [package]\fP"

.PP
\fBPostcondició\fP
.RS 4
s'ha cridat a la classe mare d'exepció 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIt\fP Posició d'origen de la peça\&. 
.RE
.PP

.SH "Documentació de les Funcions Membre"
.PP 
.SS "\fBTipusExcepcioG\fP ExcepcioG\&.getTipus ()"

.PP
\fBPostcondició\fP
.RS 4
retorna exc 
.RE
.PP
\fBRetorna\fP
.RS 4
retorna el tipus d'exepció\&. 
.RE
.PP

.SH "Documentació de les Dades Membre"
.PP 
.SS "final \fBTipusExcepcioG\fP ExcepcioG\&.exc\fC [private]\fP"
Tipus d'exepció 

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
