.TH "src/Huma.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Huma.java \- Classe \fBHuma\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHuma\fP"
.br
.RI "Classe que representa un \fBJugador\fP controlat per un Humà\&. Fa les interaccions entre un Humà i el contolador a través del terminal\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBHuma\fP\&. 

Inerfície \fBHuma\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
