.TH "src/Json.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Json.java \- Classe \fBJson\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJson\fP"
.br
.RI "Gestiona tota la lectura i la generació dels fitxers \fBJson\fP i la creació dels objectes que aquest està involucrat\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBJson\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
