.TH "src/Jugador.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Jugador.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBJugador\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
