.TH "src/MinIMax.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MinIMax.java \- Interfície \fBMinIMax\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMinIMax\fP"
.br
.RI "Interfície que coné els mètodes que implementa l'algoritme \fBMinIMax\fP adaptat al joc dels escacs\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Interfície \fBMinIMax\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
