.TH "src/MinIMaxParalel.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MinIMaxParalel.java \- Classe \fBMinIMaxParalel\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMinIMaxParalel\fP"
.br
.RI "Classe que conté l'algoritme \fBMinIMax\fP aplicat als \fBEscacs\fP en mode Paralel\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBMinIMaxParalel\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
