.TH "src/Moviment.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Moviment.java \- Classe \fBMoviment\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoviment\fP"
.br
.RI "Interfície d'un \fBMoviment\fP d'un \fBTipusPeca\fP\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBMoviment\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
