.TH "src/MovimentRectilini.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MovimentRectilini.java \- Classe \fBMovimentRectilini\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMovimentRectilini\fP"
.br
.RI "Implementació de \fBMoviment\fP per \fBMovimentRectilini\fP\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBMovimentRectilini\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
