.TH "Pair< X, Y >" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pair< X, Y > \- Classe Contenidora de dos objectes genèrics\&.  

.SH SYNOPSIS
.br
.PP
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBPair\fP (X \fBfirst\fP, Y \fBsecond\fP)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object o)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Atributs Públics"

.in +1c
.ti -1c
.RI "X \fBfirst\fP"
.br
.ti -1c
.RI "Y \fBsecond\fP"
.br
.in -1c
.SH "Descripció Detallada"
.PP 
Classe Contenidora de dos objectes genèrics\&. 
.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "\fBPair\fP< X, Y >\&.\fBPair\fP (X first, Y second)"

.SH "Documentació de les Funcions Membre"
.PP 
.SS "boolean \fBPair\fP< X, Y >\&.equals (Object o)"

.SS "String \fBPair\fP< X, Y >\&.toString ()"

.PP
\fBPrecondició\fP
.RS 4
: Cap dels components del \fBPair\fP no pot ser null\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
: Retorna un string a partir de la representació en string dels components del pair en el format: 'first, second' 
.RE
.PP

.SH "Documentació de les Dades Membre"
.PP 
.SS "X \fBPair\fP< X, Y >\&.first"

.SS "Y \fBPair\fP< X, Y >\&.second"


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
