.TH "src/Pair.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Pair.java \- Classe \fBPair\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPair< X, Y >\fP"
.br
.RI "Classe Contenidora de dos objectes genèrics\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBPair\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
