.TH "src/Partida.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Partida.java \- Classe \fBEscacs\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPartida\fP"
.br
.RI "Motor de el conjunt de \fBEscacs\fP\&. Gestiona les jugades, el tauler, les peces\&. Executa també les jugades\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBEscacs\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
