.TH "src/Peca.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Peca.java \- Classe \fBPeca\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPeca\fP"
.br
.RI "Classe que representa una \fBPeca\fP dels escacs\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBPeca\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
