.TH "Rajola" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rajola \- \fBRajola\fP gràfica que s'utilitza per la interfície gràfica\&.  

.SH SYNOPSIS
.br
.PP
.PP
Hereta de ImageView\&.
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBRajola\fP (javafx\&.scene\&.image\&.Image imatge, int amplada)"
.br
.in -1c
.SH "Descripció Detallada"
.PP 
\fBRajola\fP gràfica que s'utilitza per la interfície gràfica\&. 


.PP
\fBAutor\fP
.RS 4
Marc Cosgaya Capel 
.PP
u1959174 
.RE
.PP

.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "Rajola\&.Rajola (javafx\&.scene\&.image\&.Image imatge, int amplada)"

.PP
.nf
@brief Constructor de Rajola.
@param imatge Imatge que representa la rajola.

.fi
.PP
 
.PP
\fBParàmetres\fP
.RS 4
\fIamplada\fP Número de pixels que tindrà la rajola\&. 
.RE
.PP


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
