.TH "src/Rajola.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rajola.java \- Classe \fBRajola\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRajola\fP"
.br
.RI "\fBRajola\fP gràfica que s'utilitza per la interfície gràfica\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBRajola\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
