.TH "src/ResultatPartida.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ResultatPartida.java \- Enum \fBResultatPartida\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBResultatPartida\fP"
.br
.RI "Enum que conté tots els possibles resultats d'una \fBPartida\fP\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Enum \fBResultatPartida\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
