.TH "src/ResultatJugada.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ResultatJugada.java \- Enum \fBResultatJugada\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBResultatJugada\fP"
.br
.RI "Conte tots els possibles estats d'una \fBJugada\fP\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Enum \fBResultatJugada\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
