.TH "ResultatJugada" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResultatJugada \- Conte tots els possibles estats d'una \fBJugada\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Atributs Públics"

.in +1c
.ti -1c
.RI "\fBtoString\fP"
.br
.in -1c
.SH "Descripció Detallada"
.PP 
Conte tots els possibles estats d'una \fBJugada\fP\&. 


.PP
\fBNota\fP
.RS 4
S'utilitza a \fBJugada\fP 
.RE
.PP
\fBAutor\fP
.RS 4
Eloi Quintana Ferrer 
.PP
u1963141 
.RE
.PP

.SH "Documentació de les Dades Membre"
.PP 
.SS "ResultatJugada\&.toString"


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
