.TH "src/Tauler.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Tauler.java \- Classe \fBTauler\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTauler\fP"
.br
.RI "Classe que representa un tauler d'\fBEscacs\fP\&. Contenidor de Caselles\&. Conté alguns mètodes de suport relacionats amb el tauler\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBTauler\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
