.TH "TipusExcepcioG" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TipusExcepcioG \- Enum que conté tots els possibles tipus d'execpcio G\&.  

.SH SYNOPSIS
.br
.PP
.SS "Atributs Públics"

.in +1c
.ti -1c
.RI "\fBtoString\fP"
.br
.in -1c
.SH "Descripció Detallada"
.PP 
Enum que conté tots els possibles tipus d'execpcio G\&. 


.PP
\fBNota\fP
.RS 4
és un Enum\&. 
.RE
.PP
\fBAutor\fP
.RS 4
Eloi Quintana Ferrer 
.PP
u1963141 
.RE
.PP

.SH "Documentació de les Dades Membre"
.PP 
.SS "TipusExcepcioG\&.toString"


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
