.TH "src/TipusPeca.java" 3 "Dl Jun 1 2020" "Version v3" "Escacs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TipusPeca.java \- Classe \fBTipusPeca\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTipusPeca\fP"
.br
.RI "Un tipus de peça configurable\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Classe \fBTipusPeca\fP\&. 


.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Escacs a partir del codi font\&.
